const express = require('express')
const app = express()
const cors = require('cors')
const PORT = 8000

app.set('view engine', 'ejs')
app.use(cors())
app.use(express.static('public'))
app.use(express.urlencoded({ extended: true }))
app.use(express.json())


const players = {
    "jon rahm": {
        "PlayerSeasonID": 5776,
        "Season": 2021,
        "PlayerID": 40001199,
        "Name": "Jon Rahm",
        "WorldGolfRank": 2,
        "WorldGolfRankLastWeek": 2,
        "Events": 76,
        "AveragePoints": 16.9,
        "TotalPoints": 827.7,
        "PointsLost": -433.1,
        "PointsGained": 530.3
    },
    "dustin johnson": {
        "PlayerSeasonID": 5775,
        "Season": 2021,
        "PlayerID": 40000015,
        "Name": "Dustin Johnson",
        "WorldGolfRank": 5,
        "WorldGolfRankLastWeek": 5,
        "Events": 67,
        "AveragePoints": 14.0,
        "TotalPoints": 600.3,
        "PointsLost": -418.2,
        "PointsGained": 229.4
    },
    "collin morikawa": {
        "PlayerSeasonID": 5779,
        "Season": 2021,
        "PlayerID": 40002471,
        "Name": "Collin Morikawa",
        "WorldGolfRank": 7,
        "WorldGolfRankLastWeek": 7,
        "Events": 81,
        "AveragePoints": 13.0,
        "TotalPoints": 677.9,
        "PointsLost": -248.0,
        "PointsGained": 491.0
    },
    "patrick cantlay": {
        "PlayerSeasonID": 5786,
        "Season": 2021,
        "PlayerID": 40000216,
        "Name": "Patrick Cantlay",
        "WorldGolfRank": 10,
        "WorldGolfRankLastWeek": 10,
        "Events": 67,
        "AveragePoints": 11.8,
        "TotalPoints": 509.0,
        "PointsLost": -256.6,
        "PointsGained": 378.1
    },
    "xander schauffele": {
        "PlayerSeasonID": 5781,
        "Season": 2021,
        "PlayerID": 40001638,
        "Name": "Xander Schauffele",
        "WorldGolfRank": 12,
        "WorldGolfRankLastWeek": 12,
        "Events": 75,
        "AveragePoints": 11.8,
        "TotalPoints": 567.9,
        "PointsLost": -307.5,
        "PointsGained": 370.6
    },
    "justin thomas": {
        "PlayerSeasonID": 5777,
        "Season": 2021,
        "PlayerID": 40001434,
        "Name": "Justin Thomas",
        "WorldGolfRank": 15,
        "WorldGolfRankLastWeek": 15,
        "Events": 81,
        "AveragePoints": 11.2,
        "TotalPoints": 583.4,
        "PointsLost": -387.3,
        "PointsGained": 313.7
    },
    "bryson deChambeau": {
        "PlayerSeasonID": 5783,
        "Season": 2021,
        "PlayerID": 40000322,
        "Name": "Bryson DeChambeau",
        "WorldGolfRank": 11,
        "WorldGolfRankLastWeek": 11,
        "Events": 78,
        "AveragePoints": 10.8,
        "TotalPoints": 541.4,
        "PointsLost": -295.5,
        "PointsGained": 317.2
    },
    "louis oosthuizen": {
        "PlayerSeasonID": 5797,
        "Season": 2021,
        "PlayerID": 40001092,
        "Name": "Louis Oosthuizen",
        "WorldGolfRank": 12,
        "WorldGolfRankLastWeek": 12,
        "Events": 73,
        "AveragePoints": 14.8,
        "TotalPoints": 446.8,
        "PointsLost": -182.6,
        "PointsGained": 341.0
    },
    "tony finau": {
        "PlayerSeasonID": 5789,
        "Season": 2021,
        "PlayerID": 40000423,
        "Name": "Tony Finau",
        "WorldGolfRank": 14,
        "WorldGolfRankLastWeek": 14,
        "Events": 81,
        "AveragePoints": 14.3,
        "TotalPoints": 478.8,
        "PointsLost": -234.7,
        "PointsGained": 386.6
    },
    "brooks koepka": {
        "PlayerSeasonID": 5782,
        "Season": 2021,
        "PlayerID": 40000007,
        "Name": "Brooks Koepka",
        "WorldGolfRank": 16,
        "WorldGolfRankLastWeek": 16,
        "Events": 65,
        "AveragePoints": 14.0,
        "TotalPoints": 379.2,
        "PointsLost": -289.4,
        "PointsGained": 319.9
    },
    "harris english": {
        "PlayerSeasonID": 5819,
        "Season": 2021,
        "PlayerID": 40000387,
        "Name": "Harris English",
        "WorldGolfRank": 17,
        "WorldGolfRankLastWeek": 17,
        "Events": 81,
        "AveragePoints": 13.8,
        "TotalPoints": 462.8,
        "PointsLost": -146.1,
        "PointsGained": 345.7
    },
    "abraham ancer": {
        "PlayerSeasonID": 5796,
        "Season": 2021,
        "PlayerID": 40000047,
        "Name": "Abraham Ancer",
        "WorldGolfRank": 19,
        "WorldGolfRankLastWeek": 19,
        "Events": 81,
        "AveragePoints": 13.6,
        "TotalPoints": 455.4,
        "PointsLost": -180.2,
        "PointsGained": 344.4
    },
    "rory mcIlroy": {
        "PlayerSeasonID": 5778,
        "Season": 2021,
        "PlayerID": 40000965,
        "Name": "Rory McIlroy",
        "WorldGolfRank": 20,
        "WorldGolfRankLastWeek": 20,
        "Events": 78,
        "AveragePoints": 13.5,
        "TotalPoints": 433.0,
        "PointsLost": -356.9,
        "PointsGained": 289.4
    },
    "viktor hovland": {
        "PlayerSeasonID": 5805,
        "Season": 2021,
        "PlayerID": 40003218,
        "Name": "Viktor Hovland",
        "WorldGolfRank": 22,
        "WorldGolfRankLastWeek": 23,
        "Events": 81,
        "AveragePoints": 13.3,
        "TotalPoints": 446.0,
        "PointsLost": -167.3,
        "PointsGained": 310.7
    },
    "jordan spieth": {
        "PlayerSeasonID": 5841,
        "Season": 2021,
        "PlayerID": 40000004,
        "Name": "Jordan Spieth",
        "WorldGolfRank": 23,
        "WorldGolfRankLastWeek": 22,
        "Events": 76,
        "AveragePoints": 13.1,
        "TotalPoints": 412.3,
        "PointsLost": -112.4,
        "PointsGained": 404.3
    },
    "daniel berger": {
        "PlayerSeasonID": 5787,
        "Season": 2021,
        "PlayerID": 40000115,
        "Name": "Daniel Berger",
        "WorldGolfRank": 25,
        "WorldGolfRankLastWeek": 28,
        "Events": 72,
        "AveragePoints": 12.6,
        "TotalPoints": 372.7,
        "PointsLost": -171.5,
        "PointsGained": 229.1
    },
    "tyrrell hatton": {
        "PlayerSeasonID": 5788,
        "Season": 2021,
        "PlayerID": 40000596,
        "Name": "Tyrrell Hatton",
        "WorldGolfRank": 26,
        "WorldGolfRankLastWeek": 25,
        "Events": 70,
        "AveragePoints": 12.6,
        "TotalPoints": 364.5,
        "PointsLost": -245.4,
        "PointsGained": 160.3
    },
    "hideki matsuyama": {
        "PlayerSeasonID": 5793,
        "Season": 2021,
        "PlayerID": 40000017,
        "Name": "Hideki Matsuyama",
        "WorldGolfRank": 28,
        "WorldGolfRankLastWeek": 26,
        "Events": 81,
        "AveragePoints": 12.4,
        "TotalPoints": 413.2,
        "PointsLost": -213.1,
        "PointsGained": 295.0
    },
    "patrick reed": {
        "PlayerSeasonID": 5784,
        "Season": 2021,
        "PlayerID": 40000002,
        "Name": "Patrick Reed",
        "WorldGolfRank": 30,
        "WorldGolfRankLastWeek": 30,
        "Events": 81,
        "AveragePoints": 12.2,
        "TotalPoints": 408.6,
        "PointsLost": -297.1,
        "PointsGained": 238.4
    },
    "webb simpson": {
        "PlayerSeasonID": 5780,
        "Season": 2021,
        "PlayerID": 40001313,
        "Name": "Webb Simpson",
        "WorldGolfRank": 31,
        "WorldGolfRankLastWeek": 31,
        "Events": 65,
        "AveragePoints": 11.7,
        "TotalPoints": 315.0,
        "PointsLost": -270.1,
        "PointsGained": 137.1
    },
    "scott scheffler": {
        "PlayerSeasonID": 5803,
        "Season": 2021,
        "PlayerID": 40001274,
        "Name": "Scott Scheffler",
        "WorldGolfRank": 33,
        "WorldGolfRankLastWeek": 33,
        "Events": 81,
        "AveragePoints": 11.6,
        "TotalPoints": 389.1,
        "PointsLost": -153.3,
        "PointsGained": 294.1
    },
    "paul casey": {
        "PlayerSeasonID": 5795,
        "Season": 2021,
        "PlayerID": 40000006,
        "Name": "Paul Casey",
        "WorldGolfRank": 34,
        "WorldGolfRankLastWeek": 34,
        "Events": 78,
        "AveragePoints": 10.8,
        "TotalPoints": 347.4,
        "PointsLost": -203.4,
        "PointsGained": 284.0
    },
    "cameron smith": {
        "PlayerSeasonID": 5823,
        "Season": 2021,
        "PlayerID": 40001333,
        "Name": "Cameron Smith",
        "WorldGolfRank": 36,
        "WorldGolfRankLastWeek": 36,
        "Events": 79,
        "AveragePoints": 10.6,
        "TotalPoints": 348.6,
        "PointsLost": -140.2,
        "PointsGained": 229.6
    },
    "kevin na": {
        "PlayerSeasonID": 5808,
        "Season": 2021,
        "PlayerID": 40001044,
        "Name": "Kevin Na",
        "WorldGolfRank": 37,
        "WorldGolfRankLastWeek": 47,
        "Events": 81,
        "AveragePoints": 10.3,
        "TotalPoints": 344.0,
        "PointsLost": -154.0,
        "PointsGained": 294.1
    },
    "sam burns": {
        "PlayerSeasonID": 5944,
        "Season": 2021,
        "PlayerID": 40000194,
        "Name": "Sam Burns",
        "WorldGolfRank": 39,
        "WorldGolfRankLastWeek": 39,
        "Events": 76,
        "AveragePoints": 9.9,
        "TotalPoints": 311.8,
        "PointsLost": -62.6,
        "PointsGained": 293.5
    },
    "matthew fitzpatrick": {
        "PlayerSeasonID": 5791,
        "Season": 2021,
        "PlayerID": 40000430,
        "Name": "Matthew Fitzpatrick",
        "WorldGolfRank": 40,
        "WorldGolfRankLastWeek": 37,
        "Events": 81,
        "AveragePoints": 9.9,
        "TotalPoints": 329.7,
        "PointsLost": -214.3,
        "PointsGained": 174.0
    },
    "jason kokrak": {
        "PlayerSeasonID": 5829,
        "Season": 2021,
        "PlayerID": 40000785,
        "Name": "Jason Kokrak",
        "WorldGolfRank": 42,
        "WorldGolfRankLastWeek": 40,
        "Events": 81,
        "AveragePoints": 9.8,
        "TotalPoints": 326.5,
        "PointsLost": -146.9,
        "PointsGained": 211.8
    },
    "billy horschel": {
        "PlayerSeasonID": 5807,
        "Season": 2021,
        "PlayerID": 40000016,
        "Name": "Billy Horschel",
        "WorldGolfRank": 44,
        "WorldGolfRankLastWeek": 44,
        "Events": 81,
        "AveragePoints": 9.3,
        "TotalPoints": 312.2,
        "PointsLost": -151.7,
        "PointsGained": 245.3
    },
    "sung-jae im": {
        "PlayerSeasonID": 5798,
        "Season": 2021,
        "PlayerID": 40002605,
        "Name": "Sung-Jae Im",
        "WorldGolfRank": 45,
        "WorldGolfRankLastWeek": 42,
        "Events": 81,
        "AveragePoints": 9.3,
        "TotalPoints": 312.1,
        "PointsLost": -205.9,
        "PointsGained": 184.5
    },
    "joaquin niemann": {
        "PlayerSeasonID": 5824,
        "Season": 2021,
        "PlayerID": 40002644,
        "Name": "Joaquin Niemann",
        "WorldGolfRank": 47,
        "WorldGolfRankLastWeek": 45,
        "Events": 81,
        "AveragePoints": 8.8,
        "TotalPoints": 293.7,
        "PointsLost": -140.4,
        "PointsGained": 233.3
    },
    "will zalatoris": {
        "PlayerSeasonID": 5916,
        "Season": 2021,
        "PlayerID": 40001620,
        "Name": "Will Zalatoris",
        "WorldGolfRank": 48,
        "WorldGolfRankLastWeek": 48,
        "Events": 78,
        "AveragePoints": 7.9,
        "TotalPoints": 255.3,
        "PointsLost": -77.6,
        "PointsGained": 205.6
    },
    "corey conners": {
        "PlayerSeasonID": 5844,
        "Season": 2021,
        "PlayerID": 40000270,
        "Name": "Corey Conners",
        "WorldGolfRank": 50,
        "WorldGolfRankLastWeek": 51,
        "Events": 81,
        "AveragePoints": 7.8,
        "TotalPoints": 261.7,
        "PointsLost": -117.1,
        "PointsGained": 205.2
    },
    "lee westwood": {
        "PlayerSeasonID": 5816,
        "Season": 2021,
        "PlayerID": 40001543,
        "Name": "Lee Westwood",
        "WorldGolfRank": 51,
        "WorldGolfRankLastWeek": 50,
        "Events": 81,
        "AveragePoints": 7.6,
        "TotalPoints": 254.8,
        "PointsLost": -128.0,
        "PointsGained": 175.9
    },
    "phil mickelson": {
        "PlayerSeasonID": 5825,
        "Season": 2021,
        "PlayerID": 40000991,
        "Name": "Phil Mickelson",
        "WorldGolfRank": 53,
        "WorldGolfRankLastWeek": 54,
        "Events": 73,
        "AveragePoints": 7.5,
        "TotalPoints": 227.5,
        "PointsLost": -81.6,
        "PointsGained": 184.7
    },
    "kevin kisner": {
        "PlayerSeasonID": 5804,
        "Season": 2021,
        "PlayerID": 40000770,
        "Name": "Kevin Kisner",
        "WorldGolfRank": 54,
        "WorldGolfRankLastWeek": 53,
        "Events": 81,
        "AveragePoints": 7.4,
        "TotalPoints": 248.4,
        "PointsLost": -159.4,
        "PointsGained": 129.8
    },
    "ryan palmer": {
        "PlayerSeasonID": 5809,
        "Season": 2021,
        "PlayerID": 40001107,
        "Name": "Ryan Palmer",
        "WorldGolfRank": 56,
        "WorldGolfRankLastWeek": 56,
        "Events": 73,
        "AveragePoints": 7.2,
        "TotalPoints": 218.0,
        "PointsLost": -124.9,
        "PointsGained": 133.3
    },
    "tommy fleetwood": {
        "PlayerSeasonID": 5790,
        "Season": 2021,
        "PlayerID": 40000432,
        "Name": "Tommy Fleetwood",
        "WorldGolfRank": 58,
        "WorldGolfRankLastWeek": 59,
        "Events": 81,
        "AveragePoints": 7.2,
        "TotalPoints": 238.9,
        "PointsLost": -222.0,
        "PointsGained": 121.1
    },
    "marc leishman": {
        "PlayerSeasonID": 5800,
        "Season": 2021,
        "PlayerID": 40000842,
        "Name": "Marc Leishman",
        "WorldGolfRank": 59,
        "WorldGolfRankLastWeek": 61,
        "Events": 76,
        "AveragePoints": 6.6,
        "TotalPoints": 208.5,
        "PointsLost": -155.9,
        "PointsGained": 133.6
    },
    "adam scott": {
        "PlayerSeasonID": 5785,
        "Season": 2021,
        "PlayerID": 40000010,
        "Name": "Adam Scott",
        "WorldGolfRank": 61,
        "WorldGolfRankLastWeek": 58,
        "Events": 62,
        "AveragePoints": 6.6,
        "TotalPoints": 169.6,
        "PointsLost": -176.3,
        "PointsGained": 92.8
    },
    "shane lowry": {
        "PlayerSeasonID": 5802,
        "Season": 2021,
        "PlayerID": 40000890,
        "Name": "Shane Lowry",
        "WorldGolfRank": 62,
        "WorldGolfRankLastWeek": 62,
        "Events": 81,
        "AveragePoints": 6.5,
        "TotalPoints": 216.9,
        "PointsLost": -178.8,
        "PointsGained": 163.3
    },
    "sergio garcia": {
        "PlayerSeasonID": 5818,
        "Season": 2021,
        "PlayerID": 40000479,
        "Name": "Sergio Garcia",
        "WorldGolfRank": 64,
        "WorldGolfRankLastWeek": 75,
        "Events": 81,
        "AveragePoints": 6.3,
        "TotalPoints": 212.0,
        "PointsLost": -126.1,
        "PointsGained": 149.7
    },
    "max homa": {
        "PlayerSeasonID": 5852,
        "Season": 2021,
        "PlayerID": 40000638,
        "Name": "Max Homa",
        "WorldGolfRank": 65,
        "WorldGolfRankLastWeek": 64,
        "Events": 81,
        "AveragePoints": 6.3,
        "TotalPoints": 212.0,
        "PointsLost": -101.8,
        "PointsGained": 197.5
    },
    "brian harman": {
        "PlayerSeasonID": 5883,
        "Season": 2021,
        "PlayerID": 40000585,
        "Name": "Brian Harman",
        "WorldGolfRank": 67,
        "WorldGolfRankLastWeek": 65,
        "Events": 81,
        "AveragePoints": 6.3,
        "TotalPoints": 209.3,
        "PointsLost": -85.2,
        "PointsGained": 171.5
    },
    "christiaan bezuidenhout": {
        "PlayerSeasonID": 5826,
        "Season": 2021,
        "PlayerID": 40002583,
        "Name": "Christiaan Bezuidenhout",
        "WorldGolfRank": 69,
        "WorldGolfRankLastWeek": 78,
        "Events": 81,
        "AveragePoints": 6.2,
        "TotalPoints": 207.4,
        "PointsLost": -130.5,
        "PointsGained": 94.7
    },
    "justin rose": {
        "PlayerSeasonID": 5792,
        "Season": 2021,
        "PlayerID": 40000013,
        "Name": "Justin Rose",
        "WorldGolfRank": 70,
        "WorldGolfRankLastWeek": 70,
        "Events": 70,
        "AveragePoints": 6.1,
        "TotalPoints": 176.5,
        "PointsLost": -163.8,
        "PointsGained": 116.9
    },
    "stewart cink": {
        "PlayerSeasonID": 6092,
        "Season": 2021,
        "PlayerID": 40000248,
        "Name": "Stewart Cink",
        "WorldGolfRank": 72,
        "WorldGolfRankLastWeek": 72,
        "Events": 75,
        "AveragePoints": 6.0,
        "TotalPoints": 186.8,
        "PointsLost": -46.2,
        "PointsGained": 160.0
    },
    "garrick higgo": {
        "PlayerSeasonID": 5959,
        "Season": 2021,
        "PlayerID": 40003542,
        "Name": "Garrick Higgo",
        "WorldGolfRank": 73,
        "WorldGolfRankLastWeek": 67,
        "Events": 81,
        "AveragePoints": 6.0,
        "TotalPoints": 201.3,
        "PointsLost": -52.8,
        "PointsGained": 157.9
    },
    "ian poulter": {
        "PlayerSeasonID": 5833,
        "Season": 2021,
        "PlayerID": 40001174,
        "Name": "Ian Poulter",
        "WorldGolfRank": 75,
        "WorldGolfRankLastWeek": 73,
        "Events": 81,
        "AveragePoints": 6.0,
        "TotalPoints": 199.8,
        "PointsLost": -109.4,
        "PointsGained": 131.1
    },
    "matthew wolff": {
        "PlayerSeasonID": 5810,
        "Season": 2021,
        "PlayerID": 40003460,
        "Name": "Matthew Wolff",
        "WorldGolfRank": 76,
        "WorldGolfRankLastWeek": 69,
        "Events": 73,
        "AveragePoints": 6.0,
        "TotalPoints": 180.4,
        "PointsLost": -141.1,
        "PointsGained": 34.4
    },
    "si woo kim": {
        "PlayerSeasonID": 5860,
        "Season": 2021,
        "PlayerID": 40000764,
        "Name": "Si Woo Kim",
        "WorldGolfRank": 78,
        "WorldGolfRankLastWeek": 76,
        "Events": 81,
        "AveragePoints": 5.9,
        "TotalPoints": 198.4,
        "PointsLost": -91.0,
        "PointsGained": 170.1
    },
    "victor perez": {
        "PlayerSeasonID": 5827,
        "Season": 2021,
        "PlayerID": 40002711,
        "Name": "Victor Perez",
        "WorldGolfRank": 79,
        "WorldGolfRankLastWeek": 79,
        "Events": 72,
        "AveragePoints": 5.7,
        "TotalPoints": 169.0,
        "PointsLost": -122.7,
        "PointsGained": 83.6
    },
    "lucas herbert": {
        "PlayerSeasonID": 5853,
        "Season": 2021,
        "PlayerID": 40002752,
        "Name": "Lucas Herbert",
        "WorldGolfRank": 81,
        "WorldGolfRankLastWeek": 81,
        "Events": 65,
        "AveragePoints": 5.6,
        "TotalPoints": 152.6,
        "PointsLost": -62.4,
        "PointsGained": 98.8
    },
    "erik van rooyen": {
        "PlayerSeasonID": 5822,
        "Season": 2021,
        "PlayerID": 40002547,
        "Name": "Erik Van Rooyen",
        "WorldGolfRank": 83,
        "WorldGolfRankLastWeek": 86,
        "Events": 81,
        "AveragePoints": 5.6,
        "TotalPoints": 188.5,
        "PointsLost": -112.9,
        "PointsGained": 128.7
    },
    "robert macIntyre": {
        "PlayerSeasonID": 5861,
        "Season": 2021,
        "PlayerID": 40002950,
        "Name": "Robert MacIntyre",
        "WorldGolfRank": 84,
        "WorldGolfRankLastWeek": 83,
        "Events": 81,
        "AveragePoints": 5.6,
        "TotalPoints": 186.2,
        "PointsLost": -103.5,
        "PointsGained": 125.7
    },
    "mackenzie hughes": {
        "PlayerSeasonID": 5831,
        "Season": 2021,
        "PlayerID": 40000659,
        "Name": "Mackenzie Hughes",
        "WorldGolfRank": 86,
        "WorldGolfRankLastWeek": 84,
        "Events": 81,
        "AveragePoints": 5.6,
        "TotalPoints": 185.6,
        "PointsLost": -94.8,
        "PointsGained": 100.6
    },
    "kevin streelman": {
        "PlayerSeasonID": 5821,
        "Season": 2021,
        "PlayerID": 40001390,
        "Name": "Kevin Streelman",
        "WorldGolfRank": 87,
        "WorldGolfRankLastWeek": 87,
        "Events": 81,
        "AveragePoints": 5.4,
        "TotalPoints": 181.2,
        "PointsLost": -106.1,
        "PointsGained": 111.0
    },
    "branden grace": {
        "PlayerSeasonID": 5877,
        "Season": 2021,
        "PlayerID": 40000527,
        "Name": "Branden Grace",
        "WorldGolfRank": 89,
        "WorldGolfRankLastWeek": 89,
        "Events": 81,
        "AveragePoints": 5.3,
        "TotalPoints": 177.1,
        "PointsLost": -71.1,
        "PointsGained": 143.2
    },
    "kyoung-hoon lee": {
        "PlayerSeasonID": 5988,
        "Season": 2021,
        "PlayerID": 40000836,
        "Name": "Kyoung-Hoon Lee",
        "WorldGolfRank": 90,
        "WorldGolfRankLastWeek": 90,
        "Events": 81,
        "AveragePoints": 5.2,
        "TotalPoints": 172.7,
        "PointsLost": -46.5,
        "PointsGained": 169.9
    },
    "russell henley": {
        "PlayerSeasonID": 5896,
        "Season": 2021,
        "PlayerID": 40000615,
        "Name": "Russell Henley",
        "WorldGolfRank": 92,
        "WorldGolfRankLastWeek": 92,
        "Events": 81,
        "AveragePoints": 5.1,
        "TotalPoints": 169.3,
        "PointsLost": -80.7,
        "PointsGained": 91.0
    },
    "min woo lee": {
        "PlayerSeasonID": 5911,
        "Season": 2021,
        "PlayerID": 40002925,
        "Name": "Min Woo Lee",
        "WorldGolfRank": 93,
        "WorldGolfRankLastWeek": 100,
        "Events": 62,
        "AveragePoints": 5.0,
        "TotalPoints": 129.6,
        "PointsLost": -36.0,
        "PointsGained": 104.6
    },
    "charley hoffman": {
        "PlayerSeasonID": 5917,
        "Season": 2021,
        "PlayerID": 40000632,
        "Name": "Charley Hoffman",
        "WorldGolfRank": 95,
        "WorldGolfRankLastWeek": 95,
        "Events": 81,
        "AveragePoints": 5.0,
        "TotalPoints": 166.4,
        "PointsLost": -63.7,
        "PointsGained": 139.8
    },
    "alexander noren": {
        "PlayerSeasonID": 5864,
        "Season": 2021,
        "PlayerID": 40001064,
        "Name": "Alexander Noren",
        "WorldGolfRank": 97,
        "WorldGolfRankLastWeek": 97,
        "Events": 81,
        "AveragePoints": 5.0,
        "TotalPoints": 166.0,
        "PointsLost": -71.3,
        "PointsGained": 117.4
    },
    "bernd wiesberger": {
        "PlayerSeasonID": 5806,
        "Season": 2021,
        "PlayerID": 40001560,
        "Name": "Bernd Wiesberger",
        "WorldGolfRank": 98,
        "WorldGolfRankLastWeek": 93,
        "Events": 81,
        "AveragePoints": 4.9,
        "TotalPoints": 165.7,
        "PointsLost": -138.4,
        "PointsGained": 103.5
    },
    "cameron davis": {
        "PlayerSeasonID": 5971,
        "Season": 2021,
        "PlayerID": 40002474,
        "Name": "Cameron Davis",
        "WorldGolfRank": 100,
        "WorldGolfRankLastWeek": 98,
        "Events": 81,
        "AveragePoints": 4.8,
        "TotalPoints": 162.1,
        "PointsLost": -43.8,
        "PointsGained": 143.0
    },
    "bubba watson": {
        "PlayerSeasonID": 5838,
        "Season": 2021,
        "PlayerID": 40000001,
        "Name": "Bubba Watson",
        "WorldGolfRank": 101,
        "WorldGolfRankLastWeek": 104,
        "Events": 73,
        "AveragePoints": 4.8,
        "TotalPoints": 144.6,
        "PointsLost": -96.6,
        "PointsGained": 69.4
    },
    "carlos ortiz": {
        "PlayerSeasonID": 5922,
        "Season": 2021,
        "PlayerID": 40001097,
        "Name": "Carlos Ortiz",
        "WorldGolfRank": 103,
        "WorldGolfRankLastWeek": 101,
        "Events": 81,
        "AveragePoints": 4.7,
        "TotalPoints": 158.1,
        "PointsLost": -87.6,
        "PointsGained": 82.0
    },
    "sebastian munoz": {
        "PlayerSeasonID": 5849,
        "Season": 2021,
        "PlayerID": 40001682,
        "Name": "Sebastian Munoz",
        "WorldGolfRank": 104,
        "WorldGolfRankLastWeek": 103,
        "Events": 81,
        "AveragePoints": 4.7,
        "TotalPoints": 157.8,
        "PointsLost": -94.9,
        "PointsGained": 99.2
    },
    "chris kirk": {
        "PlayerSeasonID": 6032,
        "Season": 2021,
        "PlayerID": 40000011,
        "Name": "Chris Kirk",
        "WorldGolfRank": 106,
        "WorldGolfRankLastWeek": 111,
        "Events": 62,
        "AveragePoints": 4.7,
        "TotalPoints": 120.5,
        "PointsLost": -35.0,
        "PointsGained": 116.0
    },
    "cameron champ": {
        "PlayerSeasonID": 5848,
        "Season": 2021,
        "PlayerID": 40002650,
        "Name": "Cameron Champ",
        "WorldGolfRank": 107,
        "WorldGolfRankLastWeek": 109,
        "Events": 81,
        "AveragePoints": 4.7,
        "TotalPoints": 156.6,
        "PointsLost": -81.4,
        "PointsGained": 94.1
    },
    "matt wallace": {
        "PlayerSeasonID": 5820,
        "Season": 2021,
        "PlayerID": 40002569,
        "Name": "Matt Wallace",
        "WorldGolfRank": 109,
        "WorldGolfRankLastWeek": 106,
        "Events": 81,
        "AveragePoints": 4.7,
        "TotalPoints": 156.3,
        "PointsLost": -128.6,
        "PointsGained": 93.9
    },
    "guido migliozzi": {
        "PlayerSeasonID": 5928,
        "Season": 2021,
        "PlayerID": 40002829,
        "Name": "Guido Migliozzi",
        "WorldGolfRank": 111,
        "WorldGolfRankLastWeek": 107,
        "Events": 75,
        "AveragePoints": 4.6,
        "TotalPoints": 142.3,
        "PointsLost": -50.1,
        "PointsGained": 132.3
    },
    "charl schwartzel": {
        "PlayerSeasonID": 5965,
        "Season": 2021,
        "PlayerID": 40001290,
        "Name": "Charl Schwartzel",
        "WorldGolfRank": 112,
        "WorldGolfRankLastWeek": 112,
        "Events": 64,
        "AveragePoints": 4.5,
        "TotalPoints": 119.1,
        "PointsLost": -30.1,
        "PointsGained": 96.5
    },
    "emiliano grillo": {
        "PlayerSeasonID": 5921,
        "Season": 2021,
        "PlayerID": 40000540,
        "Name": "Emiliano Grillo",
        "WorldGolfRank": 114,
        "WorldGolfRankLastWeek": 114,
        "Events": 81,
        "AveragePoints": 4.5,
        "TotalPoints": 149.6,
        "PointsLost": -58.7,
        "PointsGained": 121.6
    },
    "cameron tringale": {
        "PlayerSeasonID": 5951,
        "Season": 2021,
        "PlayerID": 40001460,
        "Name": "Cameron Tringale",
        "WorldGolfRank": 115,
        "WorldGolfRankLastWeek": 115,
        "Events": 79,
        "AveragePoints": 4.5,
        "TotalPoints": 146.1,
        "PointsLost": -59.0,
        "PointsGained": 106.6
    },
    "matt jones": {
        "PlayerSeasonID": 5868,
        "Season": 2021,
        "PlayerID": 40000720,
        "Name": "Matt Jones",
        "WorldGolfRank": 117,
        "WorldGolfRankLastWeek": 117,
        "Events": 81,
        "AveragePoints": 4.4,
        "TotalPoints": 147.9,
        "PointsLost": -80.8,
        "PointsGained": 120.5
    },
    "talor gooch": {
        "PlayerSeasonID": 5915,
        "Season": 2021,
        "PlayerID": 40000518,
        "Name": "Talor Gooch",
        "WorldGolfRank": 118,
        "WorldGolfRankLastWeek": 118,
        "Events": 81,
        "AveragePoints": 4.4,
        "TotalPoints": 146.0,
        "PointsLost": -70.8,
        "PointsGained": 91.4
    },
    "thomas detry": {
        "PlayerSeasonID": 5854,
        "Season": 2021,
        "PlayerID": 40002573,
        "Name": "Thomas Detry",
        "WorldGolfRank": 120,
        "WorldGolfRankLastWeek": 120,
        "Events": 81,
        "AveragePoints": 4.3,
        "TotalPoints": 145.3,
        "PointsLost": -73.6,
        "PointsGained": 86.8
    },
    "jason day": {
        "PlayerSeasonID": 5811,
        "Season": 2021,
        "PlayerID": 40000314,
        "Name": "Jason Day",
        "WorldGolfRank": 121,
        "WorldGolfRankLastWeek": 126,
        "Events": 70,
        "AveragePoints": 4.3,
        "TotalPoints": 125.0,
        "PointsLost": -105.1,
        "PointsGained": 49.4
    },
    "harold varner": {
        "PlayerSeasonID": 5888,
        "Season": 2021,
        "PlayerID": 40001490,
        "Name": "Harold Varner",
        "WorldGolfRank": 123,
        "WorldGolfRankLastWeek": 121,
        "Events": 81,
        "AveragePoints": 4.3,
        "TotalPoints": 144.4,
        "PointsLost": -67.0,
        "PointsGained": 110.4
    },
    "keegan bradley": {
        "PlayerSeasonID": 5863,
        "Season": 2021,
        "PlayerID": 40000152,
        "Name": "Keegan Bradley",
        "WorldGolfRank": 125,
        "WorldGolfRankLastWeek": 123,
        "Events": 81,
        "AveragePoints": 4.3,
        "TotalPoints": 143.1,
        "PointsLost": -73.1,
        "PointsGained": 114.8
    },
    "brendon todd": {
        "PlayerSeasonID": 5813,
        "Season": 2021,
        "PlayerID": 40001447,
        "Name": "Brendon Todd",
        "WorldGolfRank": 126,
        "WorldGolfRankLastWeek": 125,
        "Events": 81,
        "AveragePoints": 4.2,
        "TotalPoints": 142.3,
        "PointsLost": -97.9,
        "PointsGained": 67.7
    },
    "rasmus hojgaard": {
        "PlayerSeasonID": 5839,
        "Season": 2021,
        "PlayerID": 40003220,
        "Name": "Rasmus Hojgaard",
        "WorldGolfRank": 128,
        "WorldGolfRankLastWeek": 129,
        "Events": 81,
        "AveragePoints": 4.1,
        "TotalPoints": 138.6,
        "PointsLost": -61.9,
        "PointsGained": 89.4
    },
    "matt kuchar": {
        "PlayerSeasonID": 5801,
        "Season": 2021,
        "PlayerID": 40000014,
        "Name": "Matt Kuchar",
        "WorldGolfRank": 129,
        "WorldGolfRankLastWeek": 128,
        "Events": 78,
        "AveragePoints": 4.1,
        "TotalPoints": 132.2,
        "PointsLost": -164.3,
        "PointsGained": 77.4
    },
    "takumi kanaya": {
        "PlayerSeasonID": 6007,
        "Season": 2021,
        "PlayerID": 40002913,
        "Name": "Takumi Kanaya",
        "WorldGolfRank": 131,
        "WorldGolfRankLastWeek": 140,
        "Events": 62,
        "AveragePoints": 4.0,
        "TotalPoints": 104.4,
        "PointsLost": -40.9,
        "PointsGained": 62.2
    },
    "lucas glover": {
        "PlayerSeasonID": 5874,
        "Season": 2021,
        "PlayerID": 40000509,
        "Name": "Lucas Glover",
        "WorldGolfRank": 132,
        "WorldGolfRankLastWeek": 131,
        "Events": 81,
        "AveragePoints": 4.0,
        "TotalPoints": 135.4,
        "PointsLost": -74.4,
        "PointsGained": 100.1
    },
    "dylan frittelli": {
        "PlayerSeasonID": 5869,
        "Season": 2021,
        "PlayerID": 40002512,
        "Name": "Dylan Frittelli",
        "WorldGolfRank": 134,
        "WorldGolfRankLastWeek": 132,
        "Events": 81,
        "AveragePoints": 4.0,
        "TotalPoints": 135.1,
        "PointsLost": -84.4,
        "PointsGained": 66.1
    },
    "joel dahmen": {
        "PlayerSeasonID": 5834,
        "Season": 2021,
        "PlayerID": 40000302,
        "Name": "Joel Dahmen",
        "WorldGolfRank": 135,
        "WorldGolfRankLastWeek": 134,
        "Events": 81,
        "AveragePoints": 4.0,
        "TotalPoints": 134.3,
        "PointsLost": -94.7,
        "PointsGained": 70.0
    },
    "gary woodland": {
        "PlayerSeasonID": 5799,
        "Season": 2021,
        "PlayerID": 40001594,
        "Name": "Gary Woodland",
        "WorldGolfRank": 137,
        "WorldGolfRankLastWeek": 135,
        "Events": 78,
        "AveragePoints": 4.0,
        "TotalPoints": 129.1,
        "PointsLost": -165.0,
        "PointsGained": 79.9
    },
    "jhonattan vegas": {
        "PlayerSeasonID": 5940,
        "Season": 2021,
        "PlayerID": 40001495,
        "Name": "Jhonattan Vegas",
        "WorldGolfRank": 139,
        "WorldGolfRankLastWeek": 139,
        "Events": 78,
        "AveragePoints": 3.9,
        "TotalPoints": 126.8,
        "PointsLost": -45.9,
        "PointsGained": 113.0
    },
    "rich bland": {
        "PlayerSeasonID": 6069,
        "Season": 2021,
        "PlayerID": 40000133,
        "Name": "Rich Bland",
        "WorldGolfRank": 140,
        "WorldGolfRankLastWeek": 151,
        "Events": 79,
        "AveragePoints": 3.9,
        "TotalPoints": 128.7,
        "PointsLost": -39.0,
        "PointsGained": 101.4
    },
    "lanto griffin": {
        "PlayerSeasonID": 5845,
        "Season": 2021,
        "PlayerID": 40000535,
        "Name": "Lanto Griffin",
        "WorldGolfRank": 142,
        "WorldGolfRankLastWeek": 137,
        "Events": 81,
        "AveragePoints": 3.9,
        "TotalPoints": 130.9,
        "PointsLost": -98.9,
        "PointsGained": 70.2
    },
    "rikuya hoshino": {
        "PlayerSeasonID": 5873,
        "Season": 2021,
        "PlayerID": 40002721,
        "Name": "Rikuya Hoshino",
        "WorldGolfRank": 143,
        "WorldGolfRankLastWeek": 142,
        "Events": 62,
        "AveragePoints": 3.8,
        "TotalPoints": 98.5,
        "PointsLost": -61.1,
        "PointsGained": 66.5
    },
    "martin kaymer": {
        "PlayerSeasonID": 5862,
        "Season": 2021,
        "PlayerID": 40000741,
        "Name": "Martin Kaymer",
        "WorldGolfRank": 145,
        "WorldGolfRankLastWeek": 143,
        "Events": 67,
        "AveragePoints": 3.7,
        "TotalPoints": 103.6,
        "PointsLost": -74.6,
        "PointsGained": 56.2
    },
    "troy merritt": {
        "PlayerSeasonID": 5901,
        "Season": 2021,
        "PlayerID": 40000987,
        "Name": "Troy Merritt",
        "WorldGolfRank": 146,
        "WorldGolfRankLastWeek": 146,
        "Events": 81,
        "AveragePoints": 3.7,
        "TotalPoints": 123.8,
        "PointsLost": -55.9,
        "PointsGained": 93.2
    },
    "justin harding": {
        "PlayerSeasonID": 5891,
        "Season": 2021,
        "PlayerID": 40000583,
        "Name": "Justin Harding",
        "WorldGolfRank": 148,
        "WorldGolfRankLastWeek": 149,
        "Events": 81,
        "AveragePoints": 3.7,
        "TotalPoints": 123.3,
        "PointsLost": -66.6,
        "PointsGained": 102.9
    },
    "antoine rozner": {
        "PlayerSeasonID": 5964,
        "Season": 2021,
        "PlayerID": 40002744,
        "Name": "Antoine Rozner",
        "WorldGolfRank": 149,
        "WorldGolfRankLastWeek": 146,
        "Events": 81,
        "AveragePoints": 3.7,
        "TotalPoints": 123.1,
        "PointsLost": -62.7,
        "PointsGained": 81.0
    },
    "aaron wise": {
        "PlayerSeasonID": 5985,
        "Season": 2021,
        "PlayerID": 40002362,
        "Name": "Aaron Wise",
        "WorldGolfRank": 151,
        "WorldGolfRankLastWeek": 154,
        "Events": 72,
        "AveragePoints": 3.7,
        "TotalPoints": 108.5,
        "PointsLost": -46.9,
        "PointsGained": 62.5
    },
    "aaron rai": {
        "PlayerSeasonID": 6013,
        "Season": 2021,
        "PlayerID": 40002578,
        "Name": "Aaron Rai",
        "WorldGolfRank": 153,
        "WorldGolfRankLastWeek": 145,
        "Events": 78,
        "AveragePoints": 3.6,
        "TotalPoints": 116.6,
        "PointsLost": -62.9,
        "PointsGained": 50.8
    },
    "calum hill": {
        "PlayerSeasonID": 5943,
        "Season": 2021,
        "PlayerID": 40003156,
        "Name": "Calum Hill",
        "WorldGolfRank": 154,
        "WorldGolfRankLastWeek": 153,
        "Events": 81,
        "AveragePoints": 3.6,
        "TotalPoints": 120.8,
        "PointsLost": -47.6,
        "PointsGained": 107.8
    },
    "ryosuke kinoshita": {
        "PlayerSeasonID": 6095,
        "Season": 2021,
        "PlayerID": 40003202,
        "Name": "Ryosuke Kinoshita",
        "WorldGolfRank": 156,
        "WorldGolfRankLastWeek": 170,
        "Events": 62,
        "AveragePoints": 3.6,
        "TotalPoints": 91.8,
        "PointsLost": -23.9,
        "PointsGained": 69.4
    },
    "santiago tarrio": {
        "PlayerSeasonID": 6349,
        "Season": 2021,
        "PlayerID": 40002888,
        "Name": "Santiago Tarrio",
        "WorldGolfRank": 157,
        "WorldGolfRankLastWeek": 160,
        "Events": 65,
        "AveragePoints": 3.6,
        "TotalPoints": 96.3,
        "PointsLost": -12.6,
        "PointsGained": 81.3
    },
    "dean burmester": {
        "PlayerSeasonID": 5963,
        "Season": 2021,
        "PlayerID": 40001861,
        "Name": "Dean Burmester",
        "WorldGolfRank": 159,
        "WorldGolfRankLastWeek": 156,
        "Events": 81,
        "AveragePoints": 3.6,
        "TotalPoints": 119.3,
        "PointsLost": -46.7,
        "PointsGained": 87.6
    },
    "sam horsfield": {
        "PlayerSeasonID": 5858,
        "Season": 2021,
        "PlayerID": 40000646,
        "Name": "Sam Horsfield",
        "WorldGolfRank": 160,
        "WorldGolfRankLastWeek": 163,
        "Events": 75,
        "AveragePoints": 3.5,
        "TotalPoints": 109.8,
        "PointsLost": -57.4,
        "PointsGained": 62.8
    },
    "andy sullivan": {
        "PlayerSeasonID": 5875,
        "Season": 2021,
        "PlayerID": 40001402,
        "Name": "Andy Sullivan",
        "WorldGolfRank": 162,
        "WorldGolfRankLastWeek": 157,
        "Events": 81,
        "AveragePoints": 3.5,
        "TotalPoints": 118.6,
        "PointsLost": -79.6,
        "PointsGained": 42.6
    },
    "mito pereira": {
        "PlayerSeasonID": 6068,
        "Season": 2021,
        "PlayerID": 40001788,
        "Name": "Mito Pereira",
        "WorldGolfRank": 163,
        "WorldGolfRankLastWeek": 162,
        "Events": 75,
        "AveragePoints": 3.5,
        "TotalPoints": 109.3,
        "PointsLost": -19.6,
        "PointsGained": 95.3
    },
    "johannes veerman": {
        "PlayerSeasonID": 6078,
        "Season": 2021,
        "PlayerID": 40002587,
        "Name": "Johannes Veerman",
        "WorldGolfRank": 165,
        "WorldGolfRankLastWeek": 174,
        "Events": 72,
        "AveragePoints": 3.5,
        "TotalPoints": 103.2,
        "PointsLost": -22.3,
        "PointsGained": 84.8
    },
    "danie van tonder": {
        "PlayerSeasonID": 5993,
        "Season": 2021,
        "PlayerID": 40001486,
        "Name": "Danie Van Tonder",
        "WorldGolfRank": 167,
        "WorldGolfRankLastWeek": 159,
        "Events": 75,
        "AveragePoints": 3.5,
        "TotalPoints": 107.4,
        "PointsLost": -45.0,
        "PointsGained": 77.1
    },
    "shugo imahira": {
        "PlayerSeasonID": 5836,
        "Season": 2021,
        "PlayerID": 40002429,
        "Name": "Shugo Imahira",
        "WorldGolfRank": 168,
        "WorldGolfRankLastWeek": 232,
        "Events": 65,
        "AveragePoints": 3.5,
        "TotalPoints": 93.9,
        "PointsLost": -89.4,
        "PointsGained": 49.2
    },
    "john catlin": {
        "PlayerSeasonID": 5918,
        "Season": 2021,
        "PlayerID": 40002200,
        "Name": "John Catlin",
        "WorldGolfRank": 170,
        "WorldGolfRankLastWeek": 167,
        "Events": 81,
        "AveragePoints": 3.5,
        "TotalPoints": 116.1,
        "PointsLost": -59.3,
        "PointsGained": 56.7
    },
    "maverick mcNealy": {
        "PlayerSeasonID": 5947,
        "Season": 2021,
        "PlayerID": 40000977,
        "Name": "Maverick McNealy",
        "WorldGolfRank": 171,
        "WorldGolfRankLastWeek": 165,
        "Events": 81,
        "AveragePoints": 3.4,
        "TotalPoints": 114.2,
        "PointsLost": -48.6,
        "PointsGained": 82.2
    },
    "patton kizzire": {
        "PlayerSeasonID": 6062,
        "Season": 2021,
        "PlayerID": 40000772,
        "Name": "Patton Kizzire",
        "WorldGolfRank": 173,
        "WorldGolfRankLastWeek": 168,
        "Events": 81,
        "AveragePoints": 3.4,
        "TotalPoints": 112.9,
        "PointsLost": -36.1,
        "PointsGained": 90.9
    },
    "seamus power": {
        "PlayerSeasonID": 6152,
        "Season": 2021,
        "PlayerID": 40001685,
        "Name": "Seamus Power",
        "WorldGolfRank": 174,
        "WorldGolfRankLastWeek": 173,
        "Events": 67,
        "AveragePoints": 3.3,
        "TotalPoints": 92.8,
        "PointsLost": -17.5,
        "PointsGained": 85.2
    },
    "tom hoge": {
        "PlayerSeasonID": 5919,
        "Season": 2021,
        "PlayerID": 40000634,
        "Name": "Tom Hoge",
        "WorldGolfRank": 176,
        "WorldGolfRankLastWeek": 171,
        "Events": 81,
        "AveragePoints": 3.3,
        "TotalPoints": 111.9,
        "PointsLost": -62.4,
        "PointsGained": 65.3
    },
    "stephan jaeger": {
        "PlayerSeasonID": 6058,
        "Season": 2021,
        "PlayerID": 40000695,
        "Name": "Stephan Jaeger",
        "WorldGolfRank": 177,
        "WorldGolfRankLastWeek": 176,
        "Events": 81,
        "AveragePoints": 3.3,
        "TotalPoints": 110.5,
        "PointsLost": -32.3,
        "PointsGained": 85.6
    },
    "rory sabbatini": {
        "PlayerSeasonID": 5878,
        "Season": 2021,
        "PlayerID": 40001254,
        "Name": "Rory Sabbatini",
        "WorldGolfRank": 179,
        "WorldGolfRankLastWeek": 177,
        "Events": 81,
        "AveragePoints": 3.3,
        "TotalPoints": 110.4,
        "PointsLost": -78.7,
        "PointsGained": 81.7
    },
    "chan kim": {
        "PlayerSeasonID": 5866,
        "Season": 2021,
        "PlayerID": 40002636,
        "Name": "Chan Kim",
        "WorldGolfRank": 181,
        "WorldGolfRankLastWeek": 192,
        "Events": 62,
        "AveragePoints": 3.3,
        "TotalPoints": 84.4,
        "PointsLost": -66.8,
        "PointsGained": 41.1
    },
    "rickie fowler": {
        "PlayerSeasonID": 5812,
        "Season": 2021,
        "PlayerID": 40000003,
        "Name": "Rickie Fowler",
        "WorldGolfRank": 182,
        "WorldGolfRankLastWeek": 185,
        "Events": 70,
        "AveragePoints": 3.3,
        "TotalPoints": 94.9,
        "PointsLost": -106.6,
        "PointsGained": 56.9
    },
    "brendan steele": {
        "PlayerSeasonID": 5870,
        "Season": 2021,
        "PlayerID": 40001369,
        "Name": "Brendan Steele",
        "WorldGolfRank": 184,
        "WorldGolfRankLastWeek": 179,
        "Events": 75,
        "AveragePoints": 3.3,
        "TotalPoints": 100.9,
        "PointsLost": -61.6,
        "PointsGained": 64.8
    },
    "jt poston": {
        "PlayerSeasonID": 5846,
        "Season": 2021,
        "PlayerID": 40001971,
        "Name": "JT Poston",
        "WorldGolfRank": 185,
        "WorldGolfRankLastWeek": 184,
        "Events": 81,
        "AveragePoints": 3.2,
        "TotalPoints": 109.0,
        "PointsLost": -97.4,
        "PointsGained": 65.7
    },
    "harry higgs": {
        "PlayerSeasonID": 5905,
        "Season": 2021,
        "PlayerID": 40002004,
        "Name": "Harry Higgs",
        "WorldGolfRank": 187,
        "WorldGolfRankLastWeek": 182,
        "Events": 81,
        "AveragePoints": 3.2,
        "TotalPoints": 108.9,
        "PointsLost": -65.3,
        "PointsGained": 66.5
    },
    "adam long": {
        "PlayerSeasonID": 5850,
        "Season": 2021,
        "PlayerID": 40000877,
        "Name": "Adam Long",
        "WorldGolfRank": 188,
        "WorldGolfRankLastWeek": 181,
        "Events": 81,
        "AveragePoints": 3.2,
        "TotalPoints": 108.6,
        "PointsLost": -90.6,
        "PointsGained": 27.0
    },
    "hudson swafford": {
        "PlayerSeasonID": 6107,
        "Season": 2021,
        "PlayerID": 40001416,
        "Name": "Hudson Swafford",
        "WorldGolfRank": 190,
        "WorldGolfRankLastWeek": 188,
        "Events": 65,
        "AveragePoints": 3.2,
        "TotalPoints": 87.0,
        "PointsLost": -29.8,
        "PointsGained": 60.6
    },
    "jason scrivener": {
        "PlayerSeasonID": 5955,
        "Season": 2021,
        "PlayerID": 40001974,
        "Name": "Jason Scrivener",
        "WorldGolfRank": 192,
        "WorldGolfRankLastWeek": 187,
        "Events": 75,
        "AveragePoints": 3.2,
        "TotalPoints": 99.4,
        "PointsLost": -49.5,
        "PointsGained": 83.8
    },
    "adam hadwin": {
        "PlayerSeasonID": 5840,
        "Season": 2021,
        "PlayerID": 40000561,
        "Name": "Adam Hadwin",
        "WorldGolfRank": 193,
        "WorldGolfRankLastWeek": 190,
        "Events": 81,
        "AveragePoints": 3.1,
        "TotalPoints": 104.9,
        "PointsLost": -85.3,
        "PointsGained": 70.1
    },
    "george coetzee": {
        "PlayerSeasonID": 5920,
        "Season": 2021,
        "PlayerID": 40000259,
        "Name": "George Coetzee",
        "WorldGolfRank": 195,
        "WorldGolfRankLastWeek": 193,
        "Events": 76,
        "AveragePoints": 3.1,
        "TotalPoints": 97.1,
        "PointsLost": -68.5,
        "PointsGained": 42.6
    },
    "brandon stone": {
        "PlayerSeasonID": 5969,
        "Season": 2021,
        "PlayerID": 40001632,
        "Name": "Brandon Stone",
        "WorldGolfRank": 196,
        "WorldGolfRankLastWeek": 195,
        "Events": 81,
        "AveragePoints": 3.1,
        "TotalPoints": 103.0,
        "PointsLost": -48.0,
        "PointsGained": 78.7
    },
    "keith mitchell": {
        "PlayerSeasonID": 5895,
        "Season": 2021,
        "PlayerID": 40001680,
        "Name": "Keith Mitchell",
        "WorldGolfRank": 196,
        "WorldGolfRankLastWeek": 196,
        "Events": 81,
        "AveragePoints": 3.1,
        "TotalPoints": 103.0,
        "PointsLost": -58.4,
        "PointsGained": 85.2
    },
    "thomas pieters": {
        "PlayerSeasonID": 5851,
        "Season": 2021,
        "PlayerID": 40001157,
        "Name": "Thomas Pieters",
        "WorldGolfRank": 199,
        "WorldGolfRankLastWeek": 204,
        "Events": 64,
        "AveragePoints": 3.0,
        "TotalPoints": 79.3,
        "PointsLost": -71.2,
        "PointsGained": 44.4
    },
    "taylor moore": {
        "PlayerSeasonID": 6403,
        "Season": 2021,
        "PlayerID": 40002348,
        "Name": "Taylor Moore",
        "WorldGolfRank": 201,
        "WorldGolfRankLastWeek": 198,
        "Events": 70,
        "AveragePoints": 3.0,
        "TotalPoints": 86.9,
        "PointsLost": -7.9,
        "PointsGained": 84.3
    },
    "robert streb": {
        "PlayerSeasonID": 6101,
        "Season": 2021,
        "PlayerID": 40001388,
        "Name": "Robert Streb",
        "WorldGolfRank": 202,
        "WorldGolfRankLastWeek": 199,
        "Events": 81,
        "AveragePoints": 3.0,
        "TotalPoints": 99.4,
        "PointsLost": -47.8,
        "PointsGained": 36.6
    },
    "martin laird": {
        "PlayerSeasonID": 6112,
        "Season": 2021,
        "PlayerID": 40000802,
        "Name": "Martin Laird",
        "WorldGolfRank": 204,
        "WorldGolfRankLastWeek": 201,
        "Events": 73,
        "AveragePoints": 3.0,
        "TotalPoints": 89.5,
        "PointsLost": -53.7,
        "PointsGained": 34.8
    },
    "marcus armitage": {
        "PlayerSeasonID": 6077,
        "Season": 2021,
        "PlayerID": 40002608,
        "Name": "Marcus Armitage",
        "WorldGolfRank": 206,
        "WorldGolfRankLastWeek": 202,
        "Events": 81,
        "AveragePoints": 2.9,
        "TotalPoints": 98.0,
        "PointsLost": -27.6,
        "PointsGained": 64.6
    },
    "joohyung kim": {
        "PlayerSeasonID": 7027,
        "Season": 2021,
        "PlayerID": 40004287,
        "Name": "Joohyung Kim",
        "WorldGolfRank": 207,
        "WorldGolfRankLastWeek": 209,
        "Events": 62,
        "AveragePoints": 2.9,
        "TotalPoints": 74.9,
        "PointsLost": -45.4,
        "PointsGained": 50.1
    },
    "zach johnson": {
        "PlayerSeasonID": 5952,
        "Season": 2021,
        "PlayerID": 40000012,
        "Name": "Zach Johnson",
        "WorldGolfRank": 209,
        "WorldGolfRankLastWeek": 206,
        "Events": 70,
        "AveragePoints": 2.8,
        "TotalPoints": 82.5,
        "PointsLost": -49.0,
        "PointsGained": 32.6
    },
    "shaun norris": {
        "PlayerSeasonID": 5856,
        "Season": 2021,
        "PlayerID": 40002536,
        "Name": "Shaun Norris",
        "WorldGolfRank": 210,
        "WorldGolfRankLastWeek": 216,
        "Events": 78,
        "AveragePoints": 2.8,
        "TotalPoints": 91.3,
        "PointsLost": -69.0,
        "PointsGained": 46.4
    },
    "ryo ishikawa": {
        "PlayerSeasonID": 5889,
        "Season": 2021,
        "PlayerID": 40000686,
        "Name": "Ryo Ishikawa",
        "WorldGolfRank": 212,
        "WorldGolfRankLastWeek": 246,
        "Events": 67,
        "AveragePoints": 2.8,
        "TotalPoints": 77.7,
        "PointsLost": -57.8,
        "PointsGained": 39.8
    },
    "henrik stenson": {
        "PlayerSeasonID": 5814,
        "Season": 2021,
        "PlayerID": 40001373,
        "Name": "Henrik Stenson",
        "WorldGolfRank": 213,
        "WorldGolfRankLastWeek": 223,
        "Events": 67,
        "AveragePoints": 2.8,
        "TotalPoints": 77.3,
        "PointsLost": -91.8,
        "PointsGained": 41.1
    },
    "cheng tsung pan": {
        "PlayerSeasonID": 5913,
        "Season": 2021,
        "PlayerID": 40001109,
        "Name": "Cheng Tsung Pan",
        "WorldGolfRank": 215,
        "WorldGolfRankLastWeek": 210,
        "Events": 81,
        "AveragePoints": 2.8,
        "TotalPoints": 93.1,
        "PointsLost": -67.2,
        "PointsGained": 68.6
    },
    "matthias schwab": {
        "PlayerSeasonID": 5859,
        "Season": 2021,
        "PlayerID": 40002495,
        "Name": "Matthias Schwab",
        "WorldGolfRank": 216,
        "WorldGolfRankLastWeek": 224,
        "Events": 81,
        "AveragePoints": 2.8,
        "TotalPoints": 92.9,
        "PointsLost": -72.6,
        "PointsGained": 55.5
    },
    "greyson sigg": {
        "PlayerSeasonID": 6022,
        "Season": 2021,
        "PlayerID": 40002910,
        "Name": "Greyson Sigg",
        "WorldGolfRank": 218,
        "WorldGolfRankLastWeek": 212,
        "Events": 81,
        "AveragePoints": 2.8,
        "TotalPoints": 92.9,
        "PointsLost": -24.1,
        "PointsGained": 69.2
    },
    "yuki inamori": {
        "PlayerSeasonID": 6207,
        "Season": 2021,
        "PlayerID": 40002553,
        "Name": "Yuki Inamori",
        "WorldGolfRank": 220,
        "WorldGolfRankLastWeek": 215,
        "Events": 62,
        "AveragePoints": 2.8,
        "TotalPoints": 71.2,
        "PointsLost": -29.9,
        "PointsGained": 32.6
    },
    "richy werenski": {
        "PlayerSeasonID": 5902,
        "Season": 2021,
        "PlayerID": 40001540,
        "Name": "Richy Werenski",
        "WorldGolfRank": 221,
        "WorldGolfRankLastWeek": 213,
        "Events": 81,
        "AveragePoints": 2.7,
        "TotalPoints": 92.1,
        "PointsLost": -52.6,
        "PointsGained": 55.0
    },
    "andrew putnam": {
        "PlayerSeasonID": 5890,
        "Season": 2021,
        "PlayerID": 40001189,
        "Name": "Andrew Putnam",
        "WorldGolfRank": 223,
        "WorldGolfRankLastWeek": 220,
        "Events": 81,
        "AveragePoints": 2.7,
        "TotalPoints": 91.1,
        "PointsLost": -66.8,
        "PointsGained": 88.8
    },
    "michael thompson": {
        "PlayerSeasonID": 5885,
        "Season": 2021,
        "PlayerID": 40001439,
        "Name": "Michael Thompson",
        "WorldGolfRank": 224,
        "WorldGolfRankLastWeek": 218,
        "Events": 76,
        "AveragePoints": 2.7,
        "TotalPoints": 85.7,
        "PointsLost": -61.4,
        "PointsGained": 46.4
    },
    "kalle samooja": {
        "PlayerSeasonID": 6004,
        "Season": 2021,
        "PlayerID": 40002732,
        "Name": "Kalle Samooja",
        "WorldGolfRank": 226,
        "WorldGolfRankLastWeek": 207,
        "Events": 75,
        "AveragePoints": 2.7,
        "TotalPoints": 83.8,
        "PointsLost": -46.3,
        "PointsGained": 53.1
    },
}

app.get('/', (request, response) => {
    response.render('index.ejs')
})

app.get('/api/', (request, response) => {
    response.json(players)
})

app.get('/api/:player', (request, response) => {
    const playerName = request.params.player.toLowerCase()
    if (players[playerName]) {
        response.json(players[playerName])
    } else {
        response.json(players['unavailable'])
    }
})

app.listen(process.env.PORT || PORT, () => {
    console.log(`The server is running on port ${PORT}`)
})